version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp_project_dev_container
    volumes:
      - ../:/workspace
      - ~/.ssh/id_rsa.pub:/tmp/id_rsa.pub:ro
    ports:
      - "2222:22"
    networks:
      dev_network:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
