remote_server:
  host: 10.10.50.10
  user: joysort
  workspace: /opt/workspace/

repository:
  url: git@github.com:n0rthwood/cpp_project.git
  branch: main

development:
  build_dir: build
  test_dir: tests
  python_ext: python
